Add log function
metafacture/metafacture-fix pull request #366
Opened 2024-09-18 08:59 UTC by TobiasNx

2024-09-24 16:18 UTC, blackwinter requested changes
I've changed the implementation a little and added tests. (5d15e0e)

Still needs to be documented, though.

2024-10-02 12:20 UTC, fsteeg approved these changes

2024-10-02 12:24 UTC, blackwinter commented
The documentation doesn't match the existing structure, I'll adjust it later.

2024-10-02 13:42 UTC, blackwinter approved these changes

2024-10-09 14:20 UTC, merged