Adjust integrationtests after #127
metafacture/metafacture-fix pull request #376
Opened 2024-10-14 15:42 UTC by TobiasNx

#127

2024-10-15 08:53 UTC, blackwinter requested changes
I would prefer to leave the old integration test for `method/fromXml/toJson/replace_allInOptionalSubfieldOfRepeatedObjectsWithAsterisk` untouched and instead add a new one for #377.

2024-10-15 09:31 UTC, fsteeg reviewed
Agree about adding a new test, otherwise +1

2024-10-15 16:04 UTC, TobiasNx commented
Done

2024-10-16 07:32 UTC, fsteeg reviewed
There's a typo in the path to the new test (Asteris -> Asterisk).

2024-10-16 08:52 UTC, TobiasNx commented
Typo fixed

2024-10-16 09:01 UTC, blackwinter approved these changes
The new test name could reuse the convention from the unit tests (`ImplicitArray` instead of `WithoutCreatingArrayWithSetArray`).

2024-10-16 09:18 UTC, fsteeg approved these changes

2024-10-16 09:37 UTC, TobiasNx commented on metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_allInOptionalSubfieldOfRepeatedObjectsWithAsteriskWithoutCreatingArrayWithSetArray/todo.txt
> +See #377 . This behaviour seems to be undetected or new after #369
Adjusted as suggested. Also renamed the file as suggested.

2024-10-16 11:53 UTC, merged

2024-10-16 12:12 UTC, TobiasNx commented
I changed a set_array specific integration test, I need to change it back: metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/set_arrayWithoutValuesAndMove_fieldNewArrayOfStringsIntoArrayOfObjects/test.fix