Add new function add_array and add_hash #374
metafacture/metafacture-fix pull request #379
Opened 2024-10-16 14:53 UTC by TobiasNx

Resolves #374

This is a preparation for #309 which will change the behavior of all `set-`functions as `set_array` and `set_hash` which will not create the intermediate structure of a path.

Since we rely in context of oersi and lobid on this specific functionality I introduced `add_array` and `add_hash` which copy the current implementation of `set_array` and `set_hash`.

I also changed the tests from set_array and set_hash to add_array and add_hash since #307 will need new integration tests and java tests.

2024-10-17 12:04 UTC, blackwinter requested changes
I would suggest to change all `set_*` implementations to delegate to the corresponding `add_*` functions, so we don't have to maintain two identical implementations for each pair until the former have been replaced.

I would also argue that we should keep `set_*` where appropriate, because these are the "standard" functions; the new functions aren't supported by Catmandu (yet).

Similarly, all the tests should be left untouched in order to surface any actual behaviour changes once the `set_*` implementations are changed. Just add new ones where appropriate.

2024-10-18 11:24 UTC, fsteeg reviewed
Agree about suggestions by @blackwinter.

2024-10-29 10:22 UTC, TobiasNx commented
@blackwinter like this?

2024-11-07 09:51 UTC, blackwinter approved these changes

2024-11-07 10:26 UTC, merged